## version
version: 1.0.0

author: gang.yang
description: kafka go client

#################################
## consumer list
consumers:
  consumer:
    name : --
    brokers: [""]
    group: --
    topics: [""]
    SASL:
      enabled: true
      user: --
      password: --
    call:
      remoteUrl: --
      QoS:
        timeout: 30
        retries: 3
        commitWhenSuccess: true

#################################
## producer list
producers:
  producer:
    name: --
    brokers: [""]
    topics: [""]
    SASL:
      enabled: true
      user: --
      password: --

#################################
http:
  port: 8090
  prefix: kafka

#################################
## database
database:
  host: --
  catalog:  --
  userId: --
  password: --