## version
version: 1.0.0

author: gang.yang
description: kafka go client

#################################
## consumer list
consumers:
- name: SSP
  brokers: ["10.125.234.185:9092", "10.125.233.31:9092", "10.125.232.186:9092"]
  groupId: SSP
  topics: ["do-ssp-insurance-photo-sit"]
  SASL:
    enabled: true
    user: jZBzcshH
    password: cYjS1adKkbM2ZC0B
  remote:
    remoteUrl: ~
    QoS:
      timeout: 30
      retry: 1
      commitWhenSuccess: true
    beat:
      health: ~
      rate: 1

## database
database:
  host: 192.186.0.1
  catalog:  ~
  userId: ~
  password: ~