## version
version: 1.0.0

author: gang.yang
description: kafka go client

#################################
## consumer list
consumers:
- name: niohome-app
  brokers: ["10.132.12.11:9092", "10.132.12.7:9092", "10.132.12.8:9092"]
  groupId: niohome-app-123
  topics: ["niohome-app"]
  SASL:
    enabled: true
    user: 9740d9b27d5a
    password: 1efd388171b8
  remote:
    url: ~
    QoS:
      timeout: 30
      retry: 1
    heartbeat:
      healthUrl: ~
      timeout: 5
      rate: 1
  log:
    enabled: true

## database
database:
  host: 192.186.0.1
  catalog:  ~
  userId: ~
  password: ~